import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1776797170000 implements MigrationInterface {
    name = 'InitialSchema1776797170000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "firstName" character varying(255), "lastName" character varying(255), "avatar" text, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "prompts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "systemPrompt" text NOT NULL, "userPrompt" text, "examples" jsonb, "version" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "creatorId" uuid NOT NULL, CONSTRAINT "PK_e1e74ad82a1e159e00c8c897fa2" PRIMARY KEY ("id"), CONSTRAINT "FK_e8f2c5e88a55c89d2b0fa9a89f1" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "version" character varying(255) NOT NULL, "apiKey" text NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'enabled', "temperature" numeric NOT NULL DEFAULT '0.7', "ownerId" uuid, CONSTRAINT "PK_d85d7292c3aab5172149361e822" PRIMARY KEY ("id"), CONSTRAINT "UQ_8a3db7a8d1cf57cc267da0dac96" UNIQUE ("name", "ownerId"), CONSTRAINT "FK_61eaf44a15cc416e85dd96a02e7" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "tools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "description" text NOT NULL, "schema" jsonb NOT NULL, "category" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "config" jsonb, CONSTRAINT "PK_2a04c27d3d3701b7761b30e63c2" PRIMARY KEY ("id"), CONSTRAINT "UQ_eb2cacb9cec57bbf4e00975b6e2" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "agents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "description" text NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'active', "config" jsonb, "ownerId" uuid, "promptId" uuid, "modelId" uuid, "temperature" numeric NOT NULL DEFAULT '0.7', "promptTemplate" text, CONSTRAINT "PK_5f5c5e5c5c5e5c5e5c5c5e5c5e5e" PRIMARY KEY ("id"), CONSTRAINT "UQ_9a8b7c6d5e4f3a2b1c0d9e8f7a6b" UNIQUE ("name", "ownerId"), CONSTRAINT "FK_61eaf44a15cc416e85dd96a02e7" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_bef2c0f14c9a47a2e1c0d5f3e2a" FOREIGN KEY ("promptId") REFERENCES "prompts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7c8d9e0f1a2b3c4d5e6f7a8b9c0d" FOREIGN KEY ("modelId") REFERENCES "models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "agent_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying(50) NOT NULL DEFAULT 'pending', "input" text NOT NULL, "output" text, "error" text, "metadata" jsonb, "agentId" uuid, CONSTRAINT "PK_d3f0a6f5d1c7b8e9a0f1c2d3e4f5" PRIMARY KEY ("id"), CONSTRAINT "FK_7c8d9e0f1a2b3c4d5e6f7a8b9c0d" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "description" text NOT NULL, "code" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0b9e3bad8e9e9c8d8d8d8d8d8d8d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skill_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying(50) NOT NULL DEFAULT 'pending', "input" text, "output" text, "error" text, "skillId" uuid, CONSTRAINT "PK_1a2b3c4d5e6f7a8b9c0d1e2f3a4b" PRIMARY KEY ("id"), CONSTRAINT "FK_7a8b9c0d1e2f3a4b5c6d7e8f9a0b" FOREIGN KEY ("skillId") REFERENCES "skills"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "chains" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "description" text, "status" character varying(50) NOT NULL DEFAULT 'active', "config" jsonb, "ownerId" uuid, CONSTRAINT "PK_5b9c1c9c1c9c1c9c1c9c1c1c1c1c" PRIMARY KEY ("id"), CONSTRAINT "FK_61eaf44a15cc416e85dd96a02e7" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "chain_nodes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "position" integer NOT NULL, "type" character varying(50) NOT NULL, "config" jsonb, "chainId" uuid, CONSTRAINT "PK_7c8d9e0f1a2b3c4d5e6f7a8b9c0d" PRIMARY KEY ("id"), CONSTRAINT "FK_6b5c4d3e2f1a0b9c8d7e6f5a4b3c" FOREIGN KEY ("chainId") REFERENCES "chains"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "chain_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying(50) NOT NULL DEFAULT 'pending', "input" text, "output" text, "error" text, "metadata" jsonb, "chainId" uuid, CONSTRAINT "PK_5a6b7c8d9e0f1a2b3c4d5e6f7a8b" PRIMARY KEY ("id"), CONSTRAINT "FK_9a8b7c6d5e4f3a2b1c0d9e8f7a6b" FOREIGN KEY ("chainId") REFERENCES "chains"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "bio" text, "preferences" jsonb, "userId" uuid NOT NULL, CONSTRAINT "PK_3dd8bfc97e4a77c70971591bdcb" PRIMARY KEY ("id"), CONSTRAINT "REL_9ec62f1e9a487cfc394e41ba39" UNIQUE ("userId"), CONSTRAINT "FK_9ec62f1e9a487cfc394e41ba39c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "email_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying(255) NOT NULL, "token" character varying(255) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isVerified" boolean NOT NULL DEFAULT false, "userId" uuid, CONSTRAINT "PK_8c4d5e6f7a8b9c0d1e2f3a4b5c6d" PRIMARY KEY ("id"), CONSTRAINT "FK_5e6f7a8b9c0d1e2f3a4b5c6d7e8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`CREATE TABLE "agent_tools" ("agentsId" uuid NOT NULL, "toolsId" uuid NOT NULL, CONSTRAINT "PK_5e6f7a8b9c0d1e2f3a4b5c6d7e8" PRIMARY KEY ("agentsId", "toolsId"), CONSTRAINT "FK_9a8b7c6d5e4f3a2b1c0d9e8f7a6b" FOREIGN KEY ("agentsId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_8d7e6f5a4b3c2d1e0f9a8b7c6d5e" FOREIGN KEY ("toolsId") REFERENCES "tools"("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
        await queryRunner.query(`CREATE TABLE "agent_skills" ("agentsId" uuid NOT NULL, "skillsId" uuid NOT NULL, CONSTRAINT "PK_6f7a8b9c0d1e2f3a4b5c6d7e8f9a" PRIMARY KEY ("agentsId", "skillsId"), CONSTRAINT "FK_8b9c0d1e2f3a4b5c6d7e8f9a0b1c" FOREIGN KEY ("agentsId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_0e1f2a3b4c5d6e7f8a9b0c1d2e3f" FOREIGN KEY ("skillsId") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE CASCADE)`);
        await queryRunner.query(`CREATE INDEX "IDX_9a8b7c6d5e4f3a2b1c0d9e8f7a" ON "agent_tools" ("agentsId")`);
        await queryRunner.query(`CREATE INDEX "IDX_8d7e6f5a4b3c2d1e0f9a8b7c6d" ON "agent_tools" ("toolsId")`);
        await queryRunner.query(`CREATE INDEX "IDX_8b9c0d1e2f3a4b5c6d7e8f9a0b" ON "agent_skills" ("agentsId")`);
        await queryRunner.query(`CREATE INDEX "IDX_0e1f2a3b4c5d6e7f8a9b0c1d2e" ON "agent_skills" ("skillsId")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_0e1f2a3b4c5d6e7f8a9b0c1d2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b9c0d1e2f3a4b5c6d7e8f9a0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d7e6f5a4b3c2d1e0f9a8b7c6d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8b7c6d5e4f3a2b1c0d9e8f7a"`);
        await queryRunner.query(`DROP TABLE "agent_skills"`);
        await queryRunner.query(`DROP TABLE "agent_tools"`);
        await queryRunner.query(`DROP TABLE "email_verifications"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP TABLE "chain_runs"`);
        await queryRunner.query(`DROP TABLE "chain_nodes"`);
        await queryRunner.query(`DROP TABLE "chains"`);
        await queryRunner.query(`DROP TABLE "skill_runs"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP TABLE "agent_runs"`);
        await queryRunner.query(`DROP TABLE "agents"`);
        await queryRunner.query(`DROP TABLE "tools"`);
        await queryRunner.query(`DROP TABLE "models"`);
        await queryRunner.query(`DROP TABLE "prompts"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }
}
